name: control_tuk_tuk
description: App Flutter para controlar ganancias, odometro, ciclos y estadisticas de un Tuk Tuk.
publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/tuktuk_logo.png
    - assets/branding/tuktuk_logo_transparent.png
    - assets/branding/tuktuk_welcome.png
    - assets/branding/vrixora_solutions.png
